name: Daily Automation Newsletter

on:
  schedule:
    - cron: '30 3 * * *' # 9 AM IST
  workflow_dispatch: # Allow manual trigger

jobs:
  send_newsletter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run newsletter script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      run: python newsletter.py
